---
title: "Project"
output: html_document
date: "2025-05-15"
---

```{r}
library(readr,tidytuesdayR)
```

```         
```

```         
```

```{r}
historical_spending <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-02-13/historical_spending.csv', show_col_types = FALSE)
gifts_age <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-02-13/gifts_age.csv', show_col_types = FALSE)
gifts_gender <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-02-13/gifts_gender.csv', show_col_types = FALSE)

```

```{r}
historical_spending
```

```{r}
gifts_age
```

```{r}
gifts_gender
```

# EDA

```{r}
library(tidyverse)
library(lubridate)
library(scales)
library(skimr)
library(patchwork)
library(ggrepel)
```

```{r}
glimpse(historical_spending)
```

```{r}
skim(historical_spending)
```

```{r}
skim(gifts_age)
```

```{r}
skim(gifts_gender)
```

```{r}
sum(is.na(gifts_age)) 
```

```{r}
sum(is.na(historical_spending))
```

```{r}
gift_gender_wide <- gifts_gender %>% 
  pivot_wider(
    names_from = Gender,
    values_from = Gender
  )
gift_gender_wide
```

```{r}
gifts_gender
```

## Dataset's extention

## historical_spending 

### Compute total average spendings per year

```{r}
historical_spending_ext <- historical_spending %>% 
  mutate(AnnualSpending_tot = rowSums(.[,4:ncol(.)]))

historical_spending_ext
```

### Compute change in PerPerson spending year-over-year

```{r}
historical_spending_ext <- historical_spending_ext %>%
  arrange(Year) %>% 
  mutate(SpendingChange = case_when(
           !is.na(PerPerson) & !is.na(lag(PerPerson)) ~ {
             change <- (PerPerson - lag(PerPerson)) / lag(PerPerson)
             ifelse(change > 0, paste0("+", round(change * 100, 2), "%"),
             paste0(round(change * 100,2), "%"))
            },
           TRUE ~ NA_character_
         )
         )

historical_spending_ext
```

## gifts_age

### Compute total gift spending by age 

```{r}
gifts_age_ext <- gifts_age %>% 
  mutate(GiftSpending_tot = rowSums(.[,3:ncol(.)]))

gifts_age_ext
```

###  

## gifts_gender

### Compute total gift spending by gender

```{r}
gifts_gender_ext <- gifts_gender %>% 
  mutate(GiftSpending_tot = rowSums(.[,3:ncol(.)]))

gifts_gender_ext
```
